- name: Write apparmor conf
  template:
    src: "usr.sbin.mysqld.j2"
    dest: /etc/apparmor.d/usr.sbin.mysqld
    owner: root
    group: root
    mode: 0644
  notify: restart apparmor

- name:  Write my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Ensure MySQL conf include dir
  file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure MySQL log dir
  file:
    path: "{{ mysql_log_dir }}"
    state: directory
    owner: mysql
    group: adm
    mode: 0755

- name: Ensure MySQL slow query log file
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: touch
    owner: mysql
    group: adm
    mode: 0644

- name: Ensure MySQL err log file
  file:
    path: "{{ mysql_log_error }}"
    state: touch
    owner: mysql
    group: adm
    mode: 0644

- name: Ensure MySQL datadir
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
