- name: Is Mysql installed?
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Install Mysql packages
  apt:
    name: "{{ mysql_packages }}"
    state: present
    update_cache: yes
  when: not mysql_installed.stat.exists

- name: Which python mysql package?
  set_fact:
    mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure {{ mysql_python_package }} installed
  apt: name={{ mysql_python_package }} state=present

# Ubuntu server would start mysql after installation.
- name: Stop mysql for configuration
  service: name={{ mysql_daemon }} state=stopped